# Copyright Xilinx Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# This file contains the config for generation of cryptographic artifacts.

OrdererOrgs:
- Name: Orderer
  Domain: example.com
  Template:
    Count: 1

PeerOrgs:
- Name: Org1
  Domain: org1.example.com
  Template:
    Count: 3
  Users:
    Count: 1

- Name: Org2
  Domain: org2.example.com
  Template:
    Count: 3
  Users:
    Count: 1
